# Generated by Django 4.2.4 on 2023-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
